const INITIAL_DONE = 'INITIAL_DONE';

const CHANGE_MODE_TO_LIGHT = 'CHANGE_MODE_TO_LIGHT';
const CHANGE_MODE_TO_DARK = 'CHANGE_MODE_TO_DARK';
const UPDATE_SLIDER_VALUE = 'UPDATE_SLIDER_VALUE';
const CHANGE_LIGHT_BG_COLOR = 'CHANGE_LIGHT_BG_COLOR';

const DATA_LOADING = 'DATA_LOADING';
const DATA_DECODE = 'DATA_DECODE';
const UPDATE_TEXT_HTML_BODY = 'UPDATE_TEXT_HTML_BODY';

export {
    INITIAL_DONE,

    CHANGE_MODE_TO_LIGHT,
    CHANGE_MODE_TO_DARK,
    UPDATE_SLIDER_VALUE,
    CHANGE_LIGHT_BG_COLOR,

    DATA_LOADING,
    DATA_DECODE,
    UPDATE_TEXT_HTML_BODY,
}