const CHANGE_MODE_TO_LIGHT = 'CHANGE_MODE_TO_LIGHT';
const CHANGE_MODE_TO_DARK = 'CHANGE_MODE_TO_DARK';
const UPDATE_SLIDER_VALUE = 'UPDATE_SLIDER_VALUE';

export {
    CHANGE_MODE_TO_LIGHT,
    CHANGE_MODE_TO_DARK,
    UPDATE_SLIDER_VALUE
}