const CHANGE_MODE_TO_LIGHT = 'CHANGE_MODE_TO_LIGHT';
const CHANGE_MODE_TO_DARK = 'CHANGE_MODE_TO_DARK';
const UPDATE_SLIDER_VALUE = 'UPDATE_SLIDER_VALUE';
const CHANGE_LIGHT_BG_COLOR = 'CHANGE_LIGHT_BG_COLOR';

export {
    CHANGE_MODE_TO_LIGHT,
    CHANGE_MODE_TO_DARK,
    UPDATE_SLIDER_VALUE,
    CHANGE_LIGHT_BG_COLOR
}